name: Playwright Pytest Automation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
permissions:
  contents: read 
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Ensure Playwright Browsers
      run: playwright install chromium
      
    - name: Run Pytest in Parallel (2 Workers)
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} 
      continue-on-error: true 
      run: |
        python -m pytest -n 2 -s --alluredir=allure-results

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        allure_history: allure-history
        keep_reports: 20

    - name: Setup Pages
      if: always()
      uses: actions/configure-pages@v5

    - name: Upload Artifact to Pages
      if: always()
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'allure-history' # Folder hasil keluaran dari allure-report-action

    - name: Deploy Allure Report Web
      if: always()
      id: deployment
      uses: actions/deploy-pages@v4
